### PR TITLE
ArcFace model fixtures

### PR DESCRIPTION
**Pull request by asiryan**
Signed-off-by: asiryan <dmc5mod@yandex.ru>

Fixes this bug in ArcFace model when running on onnxruntime
`
Error "Name:'bn_data' Status Message: Invalid input scale: NumDimensions() != 3"
`

I used this python script to fix the onnxruntime exception

```python
import onnx

model = onnx.load(r'arcfaceresnet100-8.onnx')

for node in model.graph.node:
    if(node.op_type == "BatchNormalization"):
        for attr in node.attribute:
            if (attr.name == "spatial"):
                attr.i = 1
                
onnx.save(model, r'arcfaceresnet100-8_updated.onnx')
```

I also tested the model, it works fine.

### CODE REVIEW

**Comment by wenbingl** [comment]
@asiryan , do you know why the model is failing with its test data.

Running tests in /home/runner/work/models/models/ci_test_tar_dir/resnet100 for /home/runner/work/models/models/ci_test_tar_dir/resnet100/resnet100.onnx
14
/home/runner/work/models/models/ci_test_tar_dir/resnet100/test_data_set_2
15
[FAIL] arcfaceresnet100-8.onnx: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Invalid Feed Input Name:
16

**Comment by asiryan** [comment]
> @asiryan , do you know why the model is failing with its test data.
> 
> Running tests in /home/runner/work/models/models/ci_test_tar_dir/resnet100 for /home/runner/work/models/models/ci_test_tar_dir/resnet100/resnet100.onnx 14 /home/runner/work/models/models/ci_test_tar_dir/resnet100/test_data_set_2 15 [FAIL] arcfaceresnet100-8.onnx: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Invalid Feed Input Name: 16

I think there is something wrong with the test data. This is unlikely to be related to the model. I will try to make new *.pb files and pass autotests.

**Comment by liqunfu** [comment]
@asiryan 
Thank you very much for contributing to ONNX model-zoo from last year!

We are updating tutorial/model [contributor list](https://github.com/onnx/sigs/blob/main/CONTRIBUTORS) with contributors from last year. I wonder if there is anyone that has made significant contribution to models in your PR, please let me know so I can add them to the list.

Thank you!

Liqun

**Comment by asiryan** [comment]
> @asiryan Thank you very much for contributing to ONNX model-zoo from last year!
> 
> We are updating tutorial/model [contributor list](https://github.com/onnx/sigs/blob/main/CONTRIBUTORS) with contributors from last year. I wonder if there is anyone that has made significant contribution to models in your PR, please let me know so I can add them to the list.
> 
> Thank you!
> 
> Liqun

Hello! I contributed to:
https://github.com/onnx/models/blob/main/vision/body_analysis/arcface
https://github.com/onnx/models/blob/main/vision/body_analysis/ultraface
https://github.com/onnx/models/blob/main/vision/body_analysis/age_gender

and would be very grateful if you would add me to the list of contributors:
https://github.com/onnx/sigs/blob/main/CONTRIBUTORS

**Comment by liqunfu** [comment]
> > @asiryan Thank you very much for contributing to ONNX model-zoo from last year!
> > We are updating tutorial/model [contributor list](https://github.com/onnx/sigs/blob/main/CONTRIBUTORS) with contributors from last year. I wonder if there is anyone that has made significant contribution to models in your PR, please let me know so I can add them to the list.
> > Thank you!
> > Liqun
> 
> Hello! I contributed to: https://github.com/onnx/models/blob/main/vision/body_analysis/arcface https://github.com/onnx/models/blob/main/vision/body_analysis/ultraface https://github.com/onnx/models/blob/main/vision/body_analysis/age_gender
> 
> and would be very grateful if you would add me to the list of contributors: https://github.com/onnx/sigs/blob/main/CONTRIBUTORS

https://github.com/onnx/sigs/pull/166/files

**Comment by asiryan** [comment]
> > > @asiryan Thank you very much for contributing to ONNX model-zoo from last year!
> > > We are updating tutorial/model [contributor list](https://github.com/onnx/sigs/blob/main/CONTRIBUTORS) with contributors from last year. I wonder if there is anyone that has made significant contribution to models in your PR, please let me know so I can add them to the list.
> > > Thank you!
> > > Liqun
> > 
> > 
> > Hello! I contributed to: https://github.com/onnx/models/blob/main/vision/body_analysis/arcface https://github.com/onnx/models/blob/main/vision/body_analysis/ultraface https://github.com/onnx/models/blob/main/vision/body_analysis/age_gender
> > and would be very grateful if you would add me to the list of contributors: https://github.com/onnx/sigs/blob/main/CONTRIBUTORS
> 
> https://github.com/onnx/sigs/pull/166/files

Thank you very much!

**Comment by asiryan** [comment]
@liqunfu hello! You sent me an invitation to the ONNX organization, but I did not have time to respond, can you please send the invitation again? Thank you

**Comment by liqunfu** [comment]
@asiryan this PR (https://github.com/onnx/sigs/pull/166/files ) added you to the model-zoo sig. In order to engaging with other contributors, please join [slack ](https://github.com/onnx/sigs/tree/main/models-tutorials). There are other onnx related slack channels which you can find by following links at: https://github.com/onnx/sigs under Current SIGs.
thanks you.

**Comment by asiryan** [comment]
@liqunfu ok, thank you!

**Pull request merged**
