### PR TITLE
Update output for quantized models by ORT on VNNI machine 

### PR DESCRIPTION
**Pull request by jcwchen**
**Description**
- Update output for quantized models by ORT on a VNNI machine 
- Skip ORT test for quantized models in CIs, because current GitHub Action machines do not have VNNI support

**Motivation**
Closes https://github.com/onnx/models/issues/568.

### CODE REVIEW

**Comment by jcwchen** [comment]
Before merging this PR, @mszhanyi if you have time, could you please verify whether these updated output data work with your VNNI machine (or CI)?

**Comment by mszhanyi** [comment]
O

> Before merging this PR, @mszhanyi if you have time, could you please verify whether these updated output data work with your VNNI machine (or CI)?

OK

**Comment by mszhanyi** [comment]
Awesome. all tests passed

**Comment by jcwchen** [comment]
Thanks for checking these updated output data. @mszhanyi could you please review/approve this PR and let's forward it? Thank you!

**Comment by mszhanyi** [comment]
It looks that I have no permission.

**Review by mszhanyi — APPROVED** [review]

**Pull request merged**
