### PR TITLE
HF spaces demos for mask-rcnn,faster-rcnn, yolov4, DUC, and FCN

### PR DESCRIPTION
**Pull request by AK391**
followup on https://github.com/onnx/models/pull/507, added several more demos to onnx org and links to README

### CODE REVIEW

**Comment by AK391** [comment]
@jcwchen next PR for adding spaces links to onnx org is ready

**Review by jcwchen — COMMENTED** [review]
Thank you for the continuous contribution! Is the website under huggingface.co somehow down globally right now? I saw 502 Bad Gateway from my end.

**Comment by AK391** [comment]
@jcwchen thanks, yes it seems some services are down https://status.huggingface.co/

**Review by jcwchen — APPROVED** [review]
LGTM. Thanks for the effort!

**Pull request merged**
