### PR TITLE
Updating onnx model file as existing one doesn't work

### PR DESCRIPTION
**Pull request by Naveenkhasyap**
The existing onnx model file for Super Resolution model doesn't work with the Run_Super_Resolution_Model.ipynb notebook updated the working model to the same directory

### CODE REVIEW

**Comment by Naveenkhasyap** [comment]
@prasanthpul sorry I missed that will update the PR 👍

**Comment by Naveenkhasyap** [comment]
@prasanthpul updated the repo, have a look.

**Comment by prasanthpul** [comment]
im not seeing a difference between the existing file and the new one.. can you confirm whether it's supposed to be different?

**Comment by vinitra** [comment]
> LGTM. @prasanthpul it seems that Naveen's super_resolution file has been updated to use LFS, and because of that it is not showing a difference between the original model and this model in the PR.

Nevermind, I see both the model before and after the change is exactly 234 kb.

**Comment by Naveenkhasyap** [comment]
@prasanthpul you are right , we need to pull LFS files then the onnx model file works fine. I will close this PR.

**Pull request closed without merging**
