### PR TITLE
add/update faster-rcnn, mask-rcnn, ssd-mobilenetv1, ssd and yolov3 qdq/int8 models

### PR DESCRIPTION
**Pull request by yuwenzho**
Signed-off-by: yuwenzho <yuwen.zhou@intel.com>

# Faster R-CNN

## Description
This model is a real-time neural network for object detection that detects 80 different [classes](dependencies/coco_classes.txt).

## Model

|Model        |Download  | Download (with sample test data)|ONNX version|Opset version|Accuracy |
|-------------|:--------------|:--------------|:--------------|:--------------|:--------------|
|Faster R-CNN R-50-FPN      |[167.3 MB](model/FasterRCNN-10.onnx) |[158.0 MB](model/FasterRCNN-10.tar.gz) |1.5 |10 |mAP of 0.35 |
|Faster R-CNN R-50-FPN-fp32      |[168.5 MB](model/FasterRCNN-12.onnx) |[156.2 MB](model/FasterRCNN-12.tar.gz) |1.9 |12 |mAP of 0.3437 |
|Faster R-CNN R-50-FPN-int8      |[42.6 MB](model/FasterRCNN-12-int8.onnx) |[36.2 MB](model/FasterRCNN-12-int8.tar.gz) |1.9 |12 |mAP of 0.3399 |
|Faster R-CNN R-50-FPN-qdq      |[43 MB](model/FasterRCNN-12-qdq.onnx) |[29 MB](model/FasterRCNN-12-qdq.tar.gz) |1.9 |12 |mAP of 0.3397 |
> Compared with the fp32 FasterRCNN-12, int8 FasterRCNN-12's mAP decline ratio is 1.11% and performance improvement is 1.43x.
>
> Note the performance depends on the test hardware. 
> 
> Performance data here is collected with Intel® Xeon® Platinum 8280 Processor, 1s 4c per instance, CentOS Linux 8.3, data batch size is 1.

<hr>

### Input to model
Image shape `(3x'height'x'width')`

### Preprocessing steps
The images have to be loaded in to a range of [0, 255], resized, converted to BGR and then normalized using mean = [102.9801, 115.9465, 122.7717]. The transformation should preferably happen at preprocessing.

This model can take images of different sizes as input. However, to achieve best performance, it is recommended to resize the image such that both height and width are within the range of [800, 1333], and then pad the image with zeros such that both height and width are divisible by 32.

The following code shows how to preprocess the [demo image](dependencies/demo.jpg):

```python
import numpy as np
from PIL import Image

def preprocess(image):
    # Resize
    ratio = 800.0 / min(image.size[0], image.size[1])
    image = image.resize((int(ratio * image.size[0]), int(ratio * image.size[1])), Image.BILINEAR)

    # Convert to BGR
    image = np.array(image)[:, :, [2, 1, 0]].astype('float32')

    # HWC -> CHW
    image = np.transpose(image, [2, 0, 1])

    # Normalize
    mean_vec = np.array([102.9801, 115.9465, 122.7717])
    for i in range(image.shape[0]):
        image[i, :, :] = image[i, :, :] - mean_vec[i]

    # Pad to be divisible of 32
    import math
    padded_h = int(math.ceil(image.shape[1] / 32) * 32)
    padded_w = int(math.ceil(image.shape[2] / 32) * 32)

    padded_image = np.zeros((3, padded_h, padded_w), dtype=np.float32)
    padded_image[:, :image.shape[1], :image.shape[2]] = image
    image = padded_image

    return image

img = Image.open('dependencies/demo.jpg')
img_data = preprocess(img)
```

### Output of model
The model has 3 outputs.

boxes: `('nbox'x4)`, in `(xmin, ymin, xmax, ymax)`.

labels: `('nbox')`.

scores: `('nbox')`.

### Postprocessing steps

The following code shows how to patch the original image with detections and class annotations, filtered by scores:

```python
import matplotlib.pyplot as plt
import matplotlib.patches as patches

classes = [line.rstrip('\n') for line in open('coco_classes.txt')]

def display_objdetect_image(image, boxes, labels, scores, score_threshold=0.7):
    # Resize boxes
    ratio = 800.0 / min(image.size[0], image.size[1])
    boxes /= ratio

    _, ax = plt.subplots(1, figsize=(12,9))
    image = np.array(image)
    ax.imshow(image)

    # Showing boxes with score > 0.7
    for box, label, score in zip(boxes, labels, scores):
        if score > score_threshold:
            rect = patches.Rectangle((box[0], box[1]), box[2] - box[0], box[3] - box[1], linewidth=1, edgecolor='b', facecolor='none')
            ax.annotate(classes[label] + ':' + str(np.round(score, 2)), (box[0], box[1]), color='w', fontsize=12)
            ax.add_patch(rect)
    plt.show()

display_objdetect_image(img, boxes, labels, scores)
```

## Dataset (Train and validation)
The original pretrained Faster R-CNN model is from [facebookresearch/maskrcnn-benchmark](https://github.com/facebookresearch/maskrcnn-benchmark), compute mAP the same as [Detectron](https://github.com/facebookresearch/Detectron) on `coco_2014_minival` dataset from COCO, which is exactly equivalent to the `coco_2017_val` dataset.
<hr>

## Validation accuracy
Metric is COCO box mAP (averaged over IoU of 0.5:0.95), computed over 2017 COCO val data.
mAP of 0.353
<hr>

## Quantization
Faster R-CNN R-50-FPN-int8 and Faster R-CNN R-50-FPN-qdq are obtained by quantizing Faster R-CNN R-50-FPN-fp32 model. We use [Intel® Neural Compressor](https://github.com/intel/neural-compressor) with onnxruntime backend to perform quantization. View the [instructions](https://github.com/intel/neural-compressor/blob/master/examples/onnxrt/object_detection/onnx_model_zoo/faster_rcnn/quantization/ptq/README.md) to understand how to use Intel® Neural Compressor for quantization.

### Environment
onnx: 1.9.0 
onnxruntime: 1.8.0

### Prepare model
```shell
wget https://github.com/onnx/models/raw/main/vision/object_detection_segmentation/faster-rcnn/model/FasterRCNN-12.onnx
```

### Model quantize
```bash
bash run_tuning.sh --input_model=path/to/model \  # model path as *.onnx
                   --config=faster_rcnn.yaml \
                   --data_path=path/to/COCO2017 \
                   --output_model=path/to/save
```
<hr>

## Publication/Attribution
Shaoqing Ren, Kaiming He, Ross Girshick, and Jian Sun. Faster R-CNN: Towards Real-Time Object Detection with Region Proposal Networks. Conference on Neural Information Processing Systems (NIPS), 2015.

Massa, Francisco and Girshick, Ross. maskrcnn-benchmark: Fast, modular reference implementation of Instance Segmentation and Object Detection algorithms in PyTorch. [facebookresearch/maskrcnn-benchmark](https://github.com/facebookresearch/maskrcnn-benchmark).
<hr>

## References
* This model is converted from [facebookresearch/maskrcnn-benchmark](https://github.com/facebookresearch/maskrcnn-benchmark) with modifications in [repository](https://github.com/BowenBao/maskrcnn-benchmark/tree/onnx_stage).

* [Intel® Neural Compressor](https://github.com/intel/neural-compressor)
<hr>

## Contributors
* [mengniwang95](https://github.com/mengniwang95) (Intel)
* [yuwenzho](https://github.com/yuwenzho) (Intel)
* [airMeng](https://github.com/airMeng) (Intel)
* [ftian1](https://github.com/ftian1) (Intel)
* [hshen14](https://github.com/hshen14) (Intel)
<hr>

## License
MIT License
<hr>

### CODE REVIEW

**Review by jcwchen — COMMENTED** [review]
Sorry for the late review. Here is the error log from my avx512vnni machine:
```
=== Running test on ONNX models ===

 

==============Testing FasterRCNN-12-int8.tar.gz==============
LFS pull completed for vision/object_detection_segmentation/faster-rcnn/model/FasterRCNN-12-int8.tar.gz with return code= 0
Running tests in /home/chunwche/yuwenzho/models/ci_test_tar_dir/FasterRCNN-12-int8 for /home/chunwche/yuwenzho/models/ci_test_tar_dir/FasterRCNN-12-int8/FasterRCNN-12-int8.onnx
/home/chunwche/yuwenzho/models/ci_test_tar_dir/FasterRCNN-12-int8/test_data_set_0
Mismatch for 6379:
Expected:[[ 10.158569    0.        484.0289    239.2573   ]
[  4.605156    0.        218.87671   463.97827  ]
[  4.7052      4.7861404 113.54506   227.51828  ]]
Got:[[  4.233177    0.        219.31332   462.8199   ]
[ 13.373398    0.        485.06055   238.71754  ]
[  4.036461    4.5492554 113.28571   226.97647  ]]
Mismatch for 6383:
Expected:[0.08526601 0.08482158 0.0839084 ]
Got:[0.08270459 0.08148354 0.07687616]
[FAIL] FasterRCNN-12-int8.tar.gz: FAILED due to output mismatch.
LFS prune completed with return code= 0
==============Testing FasterRCNN-12-qdq.tar.gz==============
LFS pull completed for vision/object_detection_segmentation/faster-rcnn/model/FasterRCNN-12-qdq.tar.gz with return code= 0
Running tests in /home/chunwche/yuwenzho/models/ci_test_tar_dir/FasterRCNN-12-qdq for /home/chunwche/yuwenzho/models/ci_test_tar_dir/FasterRCNN-12-qdq/FasterRCNN-12-qdq.onnx
/home/chunwche/yuwenzho/models/ci_test_tar_dir/FasterRCNN-12-qdq/test_data_set_0
[FAIL] FasterRCNN-12-qdq.tar.gz: operands could not be broadcast together with shapes (24,4) (23,4)
LFS prune completed with return code= 0
==============Testing MaskRCNN-12-int8.tar.gz==============
LFS pull completed for vision/object_detection_segmentation/mask-rcnn/model/MaskRCNN-12-int8.tar.gz with return code= 0
Running tests in /home/chunwche/yuwenzho/models/ci_test_tar_dir/MaskRCNN-12-int8 for /home/chunwche/yuwenzho/models/ci_test_tar_dir/MaskRCNN-12-int8/MaskRCNN-12-int8.onnx
/home/chunwche/yuwenzho/models/ci_test_tar_dir/MaskRCNN-12-int8/test_data_set_0
[FAIL] MaskRCNN-12-int8.tar.gz: operands could not be broadcast together with shapes (4,4) (3,4)
LFS prune completed with return code= 0
==============Testing MaskRCNN-12-qdq.tar.gz==============
LFS pull completed for vision/object_detection_segmentation/mask-rcnn/model/MaskRCNN-12-qdq.tar.gz with return code= 0
Running tests in /home/chunwche/yuwenzho/models/ci_test_tar_dir/MaskRCNN-12-qdq for /home/chunwche/yuwenzho/models/ci_test_tar_dir/MaskRCNN-12-qdq/MaskRCNN-12-qdq.onnx
/home/chunwche/yuwenzho/models/ci_test_tar_dir/MaskRCNN-12-qdq/test_data_set_0
[FAIL] MaskRCNN-12-qdq.tar.gz: operands could not be broadcast together with shapes (6,4) (9,4)
LFS prune completed with return code= 0
==============Testing ssd_mobilenet_v1_12-int8.tar.gz==============
LFS pull completed for vision/object_detection_segmentation/ssd-mobilenetv1/model/ssd_mobilenet_v1_12-int8.tar.gz with return code= 0
Running tests in /home/chunwche/yuwenzho/models/ci_test_tar_dir/ssd_mobilenet_v1_12-int8 for /home/chunwche/yuwenzho/models/ci_test_tar_dir/ssd_mobilenet_v1_12-int8/ssd_mobilenet_v1_12-int8.onnx
/home/chunwche/yuwenzho/models/ci_test_tar_dir/ssd_mobilenet_v1_12-int8/test_data_set_0
PASS
[PASS] ssd_mobilenet_v1_12-int8.tar.gz is checked by onnxruntime.
LFS prune completed with return code= 0
==============Testing ssd_mobilenet_v1_13-qdq.tar.gz==============
LFS pull completed for vision/object_detection_segmentation/ssd-mobilenetv1/model/ssd_mobilenet_v1_13-qdq.tar.gz with return code= 0
Running tests in /home/chunwche/yuwenzho/models/ci_test_tar_dir/ssd_mobilenet_v1_13-qdq for /home/chunwche/yuwenzho/models/ci_test_tar_dir/ssd_mobilenet_v1_13-qdq/ssd_mobilenet_v1_13-qdq.onnx
/home/chunwche/yuwenzho/models/ci_test_tar_dir/ssd_mobilenet_v1_13-qdq/test_data_set_0
PASS
[PASS] ssd_mobilenet_v1_13-qdq.tar.gz is checked by onnxruntime.
LFS prune completed with return code= 0
==============Testing ssd-12-int8.tar.gz==============
LFS pull completed for vision/object_detection_segmentation/ssd/model/ssd-12-int8.tar.gz with return code= 0
Running tests in /home/chunwche/yuwenzho/models/ci_test_tar_dir/ssd-12-int8 for /home/chunwche/yuwenzho/models/ci_test_tar_dir/ssd-12-int8/ssd-12-int8.onnx
/home/chunwche/yuwenzho/models/ci_test_tar_dir/ssd-12-int8/test_data_set_0
[FAIL] ssd-12-int8.tar.gz: operands could not be broadcast together with shapes (1,28,4) (1,25,4)
LFS prune completed with return code= 0
==============Testing ssd-12-qdq.tar.gz==============
LFS pull completed for vision/object_detection_segmentation/ssd/model/ssd-12-qdq.tar.gz with return code= 0
Running tests in /home/chunwche/yuwenzho/models/ci_test_tar_dir/ssd-12-qdq for /home/chunwche/yuwenzho/models/ci_test_tar_dir/ssd-12-qdq/ssd-12-qdq.onnx
/home/chunwche/yuwenzho/models/ci_test_tar_dir/ssd-12-qdq/test_data_set_0
[FAIL] ssd-12-qdq.tar.gz: operands could not be broadcast together with shapes (1,22,4) (1,25,4)
LFS prune completed with return code= 0
==============Testing yolov3-12-int8.tar.gz==============
LFS pull completed for vision/object_detection_segmentation/yolov3/model/yolov3-12-int8.tar.gz with return code= 0
Running tests in /home/chunwche/yuwenzho/models/ci_test_tar_dir/yolov3-12-int8 for /home/chunwche/yuwenzho/models/ci_test_tar_dir/yolov3-12-int8/yolov3-12-int8.onnx
/home/chunwche/yuwenzho/models/ci_test_tar_dir/yolov3-12-int8/test_data_set_0
Mismatch for yolonms_layer_1/ExpandDims_1:0:
Expected:[[[-122.5129    -38.483715   19.02197    97.12024 ]
  [-253.09148   -43.705414  162.71948   108.75775 ]
  [-282.89844  -298.8799    175.78093   367.73178 ]
  ...
  [ 555.8334    632.1782    575.76666   637.6236  ]
  [ 547.48804   627.68774   580.0271    640.0046  ]
  [ 561.60114   597.9603    574.08374   669.73206 ]]]
Got:[[[-122.486404  -44.357025   15.933049  102.92634 ]
  [-272.7412    -33.824524  174.35573   101.08368 ]
  [-303.9697   -314.0318    197.41632   381.29092 ]
  ...
  [ 557.5502    630.4741    574.9427    637.50793 ]
  [ 542.3663    625.7267    585.0314    639.465   ]
  [ 560.0343    595.14667   575.72845   669.5123  ]]]
Mismatch for yolonms_layer_1/ExpandDims_3:0:
Expected:[[[1.5185035e-09 0.0000000e+00 0.0000000e+00 ... 1.9001201e-09
   0.0000000e+00 0.0000000e+00]
  [7.6525453e-12 0.0000000e+00 0.0000000e+00 ... 1.3725463e-07
   0.0000000e+00 0.0000000e+00]
  [1.0221299e-09 0.0000000e+00 0.0000000e+00 ... 4.0434347e-08
   0.0000000e+00 0.0000000e+00]
  ...
  [9.8854258e-13 0.0000000e+00 0.0000000e+00 ... 3.2684966e-13
   0.0000000e+00 0.0000000e+00]
  [1.4939161e-12 0.0000000e+00 0.0000000e+00 ... 1.8998136e-12
   0.0000000e+00 0.0000000e+00]
  [8.2867047e-13 0.0000000e+00 0.0000000e+00 ... 6.7412742e-13
   0.0000000e+00 0.0000000e+00]]]
Got:[[[0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 2.3727260e-07
   2.4329783e-09 1.0909353e-09]
  [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 4.7008859e-07
   3.0336667e-09 6.8403949e-10]
  [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 3.1135107e-06
   3.9266233e-08 5.4002886e-08]
  ...
  [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 2.1454838e-10
   1.8323121e-11 7.1480599e-12]
  [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 3.8912873e-10
   3.0784264e-11 1.4725998e-11]
  [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 2.0303759e-10
   2.4744651e-11 2.0516921e-11]]]
[FAIL] yolov3-12-int8.tar.gz: FAILED due to output mismatch.
LFS prune completed with return code= 0
In all 9 models, 7 models failed.
```

It seems that some of model and test data need to be fixed, from onnxruntime perspective.

**Comment by yuwenzho** [comment]
Hi, I have reproduced output.pb file. Please check the models.

**Review by jcwchen — APPROVED** [review]
Now they are all passed. Thank you for the updates!

**Comment by fdwr** [comment]
@yuwenzho: [ssd_mobilenet_v1_13-qdq.onnx](https://github.com/onnx/models/blob/main/validated/vision/object_detection_segmentation/ssd-mobilenetv1/model/ssd_mobilenet_v1_13-qdq.onnx) has a bug in the Resize operator (Resize__142 inside a subgraph of a Loop control flow) where the optional scales input should be named "" rather than "const_empty_float__132" with an empty tensor. From the ONNX spec, the correct way to denote missing tensors is with an empty name:

"There are two ways to leave an optional input or output unspecified: the first, available only for trailing inputs and outputs, is to simply not provide that input or output; the second method is to use an empty string in place of an input or output name."
https://github.com/onnx/onnx/blob/main/docs/IR.md#optional-inputs-and-outputs

Do you know the tool that output this file this so we can avoid generating further defective models? TY.

**Comment by yuwenzho** [comment]
> @yuwenzho: [ssd_mobilenet_v1_13-qdq.onnx](https://github.com/onnx/models/blob/main/validated/vision/object_detection_segmentation/ssd-mobilenetv1/model/ssd_mobilenet_v1_13-qdq.onnx) has a bug in the Resize operator (Resize__142 inside a subgraph of a Loop control flow) where the optional scales input should be named `""` rather than `"const_empty_float__132"` with an empty tensor. From the ONNX spec, the correct way to denote missing tensors is with an empty name:
> 
> "There are two ways to leave an optional input or output unspecified: the first, available only for trailing inputs and outputs, is to simply not provide that input or output; the second method is to use an empty string in place of an input or output name." https://github.com/onnx/onnx/blob/main/docs/IR.md#optional-inputs-and-outputs
> 
> Do you know the tool that output this file this so we can avoid generating further defective models? TY.
> 
> [(context)](https://github.com/microsoft/onnxruntime/pull/22972#issuecomment-2513505842)

Hi @fdwr, this QDQ model is an INT8 model quantized from this [FP32 model](https://github.com/onnx/models/raw/main/validated/vision/object_detection_segmentation/ssd-mobilenetv1/model/ssd_mobilenet_v1_12.onnx). I noticed the empty tensor issue also exists in FP32 model. So my suggestion is to fix the empty tensor issue in FP32 model, and then quantize the fixed model using Intel® Neural Compressor tool by following this [instructions](https://github.com/intel/neural-compressor/tree/master/examples/onnxrt/object_detection/onnx_model_zoo/ssd_mobilenet_v1/quantization/ptq_static)

**Pull request merged**
