### PR TITLE
Suport batch-size > 1 on ResNet models

### PR DESCRIPTION
**Pull request by jantonguirao**
## Description
Fixes all ResNet models so that the batch dimension is a dim_param 'N' instead of a hardcoded 1.

The changes have been applied with the following script:
batchify.py:
```
import onnx
import sys


for filename in sys.argv[1:]:
    print("Processing ", filename)
    model = onnx.load(filename)

    in0 = model.graph.input[0]
    assert 'data' in in0.name, f"Name is {in0.name}"


    if in0.type.tensor_type.shape.dim[0].dim_value == 1:
        in0.type.tensor_type.shape.dim[0].dim_param = 'N'
    else:
        assert in0.type.tensor_type.shape.dim[0].dim_param == 'N'

    out0 = model.graph.output[0]
    assert (len(model.graph.output) == 1)

    if out0.type.tensor_type.shape.dim[0].dim_value == 1:
        out0.type.tensor_type.shape.dim[0].dim_param = 'N'
    else:
        assert out0.type.tensor_type.shape.dim[0].dim_param == 'N'

    onnx.save_model(model, filename)

    new_model = onnx.load_model(filename)
    new_model.graph.input[0].type.tensor_type.shape.dim[0].dim_param == 'N'
    new_model.graph.output[0].type.tensor_type.shape.dim[0].dim_param == 'N'

    print(in0)
    print(out0)
    print("#"*50)
```

Usage:
```
cd ~/git/models/vision/classification/resnet/model
git lfs pull --include="resnet*" --exclude=""

python ~/batchify.py *onnx

for tarfile in *.tar.gz; do
    tar xzvf $tarfile
    rm $tarfile
    python ~/batchify.py */*onnx 
    tar cvzf $tarfile */
    rm -rf */
done
```

Note: This PR is based on https://github.com/onnx/models/pull/519

## Motivation

Fixes https://github.com/onnx/models/issues/509

### CODE REVIEW

**Review by jcwchen — COMMENTED** [review]
Thanks @jantonguirao for waiting. My PR has just merged. Now you can regenerate the new .tar.gz based on the new .tar.gz which I have just updated. Hopefully, there shouldn't be any issue in the CIs this time.

**Comment by jantonguirao** [comment]
@jcwchen I have now regenerated the files based on the latest code. What I did is:
1. Base my branch on https://github.com/onnx/models/pull/519, to avoid the "files that should have been pointers" issue
2. Merge latest origin/main into my branch
3. Rerun the script that I pasted on the description.

**Review by jcwchen — APPROVED** [review]
LGTM. Thank you so much for this support!

**Comment by Magnus1cheng** [comment]
Hi, I tried resnet50-v1-12-int8.onnx,  resnet50-v1-12.onnx,  and vgg16-12.onnx. I still got error message
`2022-07-07 08:25:14.477526615 [W:onnxruntime:, execution_frame.cc:811 VerifyOutputSizes] Expected shape from model of {1,1000} does not match actual shape of {128,1000} for output resnetv17_dense0_fwd` 
but when I use netron to open these .onnx files, it shows correct shape for input and output. (N,1000 for output shape).
So i'm guessing that the batchify.py script did not change the attributes internally?
Following is the code I used.
```
import io
import numpy as np
import torchvision
import time

from torch import nn
import torch.utils.model_zoo as model_zoo
import torch.onnx
import torch.nn as nn
import torch.nn.init as init
import onnx
import onnxruntime
import ssl

#torch.manual_seed(0)
#np.random.seed(0)
total_samples = 100
ssl._create_default_https_context = ssl._create_unverified_context
batch_size = 128

# Input to the model
data = np.random.rand(batch_size,3,224,224).astype(np.float32)

onnx_model = onnx.load("resnet50-v1-12.onnx")
onnx.checker.check_model(onnx_model)

ort_session = onnxruntime.InferenceSession("resnet50-v1-12.onnx",providers=['CUDAExecutionProvider'])
ort_inputs = {ort_session.get_inputs()[0].name: data}
ort_session_cpu = onnxruntime.InferenceSession("resnet50-v1-12.onnx",providers=['CPUExecutionProvider'])
ort_inputs_cpu = {ort_session_cpu.get_inputs()[0].name: data}
print("----Running ONNXRuntime----")
ort_start = time.time()
ort_latency = []
for i in range(total_samples):
    ort_start = time.time()
    ort_outs = ort_session.run(None, ort_inputs)
    ort_latency.append(time.time() - ort_start)
ort_outs_cpu = ort_session_cpu.run(None, ort_inputs_cpu)

diff = ort_outs[0]-ort_outs_cpu[0]
print("Test pass:",np.all(diff==0))
ort_avg_time = (sum(ort_latency) * 1000 / len(ort_latency))
ort_fps = batch_size/((ort_avg_time)/1000)
print("Average onnxruntime Inference time = {} ms".format(ort_avg_time, '.2f'))
print("Average onnxruntime fps = {} ".format(ort_fps, '.2f'))
```
Can you double check it again?

**Comment by jantonguirao** [comment]
It seems like the outputs/inputs definition is not enough, and we'll have to update the definitions on every node:
image

I'll look into it.

**Comment by jantonguirao** [comment]
@Magnus1cheng I have created a PR to fix the ResNet models:
https://github.com/onnx/models/pull/542

**Comment by Magnus1cheng** [comment]
Thank you for the fix. I also tried vgg16 int8 model, it also had same issue. Not sure about other models. Maybe you need to do a thorough check when you back from vacation. I'm using the .onnx models exported from torchvision model zoo, so no worries for now.
@jcwchen Hope you enjoy your vacation. :)

**Comment by jantonguirao** [comment]
@Magnus1cheng I haven't touched vgg16, since it wasn't part of the original PR. I guess that the same or a similar script could be used to batchify other models. I'll let @jcwchen bring this up with the group to see if this is something we systematically want to do to all models. Thanks!

**Pull request merged**
