### PR TITLE
Overhaul of UI, should be cleaner and has some interface scalability.

### PR DESCRIPTION
**Pull request by MaanavD**
Also using tailwind CSS, and cut down on CSS use for cleaner code, updated colors, and updated CSS units.

### CODE REVIEW

**Comment by MaanavD** [comment]
@ramkrishna2910 or @prasanthpul are you able to review this PR? I can't assign reviewers :(

**Comment by ramkrishna2910** [comment]
Hey Maanav
Thanks for the PR. I will take a look once I get to my laptop :)

**Review by ramkrishna2910 — APPROVED** [review]
Looks good!

**Comment by ramkrishna2910** [comment]
Thanks for the contribution Maanav. The improvements look good.

**Pull request merged**
