### PR TITLE
Model zoo revamp

### PR DESCRIPTION
**Pull request by ramkrishna2910**
This PR revamps the onnx model zoo by adding ~2000 new onnx files across computer vision, natural language processing, generative ai and graph machine learning.

### CODE REVIEW

**Review by jcwchen — APPROVED** [review]
Thank you so much for bringing ~2000 models into the zoo! It's existing to see there are more state-of the-art models in the Zoo.

Two concerns:
(1) About moving deprecated models into another directory "archive": please update https://github.com/onnx/models/blob/main/ONNX_HUB_MANIFEST.json accordingly with the new paths for those old models. `ONNX_HUB_MANIFEST.json` is used by onnx package's [onnx.hub](https://github.com/onnx/onnx/blob/main/docs/Hub.md). onnx.hub always downloads the models from the latest main branch of ONNX model zoo repo. That is to say, if we simply change the directory path without updating `ONNX_HUB_MANIFEST.json`, onnx.hub will be broken. The update for that .json file should be trivial and you can simply run `python workflow_scripts/generate_onnx_hub_manifest.py` under the root directory of model zoo repo with the new model paths.
(2) For now the tests for running onnx.checker and onnxruntime CPU EP were removed in this PR. Please add new corresponding tests powered by TurnkeyML ASAP to ensure these new models are all well tested. Also, we should still cover producing `ONNX_HUB_MANIFEST.json` in the CI to ensure `ONNX_HUB_MANIFEST.json` is always updated. For instance, https://github.com/onnx/models/blob/5faef4c33eba0395177850e1e31c4a6a9e634c82/.github/workflows/linux_ci.yml#L40-L44

(1) is prioritized. Please let me know if you have any issue with it. Thank you for your huge effort!

**Comment by ramkrishna2910** [comment]
The ONNX HUB manifest has been fixed to work with the new folder structure. And I have opened a separate issue #637 for adding TKML based tests for model acceptance.

**Review by jcwchen — APPROVED** [review]
Great! I tried to run an experiment as:
```
from onnx import hub
# 5ef7a840a378cdbe9014ae678e82666a35c09480 is the commit of current development branch
model = hub.load("resnet50", repo="onnx/models:5ef7a840a378cdbe9014ae678e82666a35c09480")
```
And the new path seems to work perfectly. Thank you for upadting.

**Comment by pramenku** [comment]
@ramkrishna2910 this merge has impacted QA to test DLM MIGX test. https://ontrack-internal.amd.com/browse/SWDEV-437345

**Pull request merged**
