### PR TITLE
Improve webui performance

### PR DESCRIPTION
**Pull request by venkatvellaichamy**
- refactored for readabliltiy
- improve performance

### CODE REVIEW

**Comment by ramkrishna2910** [comment]
Looks like this adds more than 2000 svg files. Do we need all those files to be in the repo?
Can we keep only the files we need?

**Comment by ramkrishna2910** [comment]
Can you also please note down the licenses of the libraries/ artifacts used in this update? We will have to ensure we are within compliance.

**Comment by venkatvellaichamy** [comment]
@ramkrishna2910 Removed unnecessary svc files and added fontawesome license file under the "fontawesome" folder

**Comment by venkatvellaichamy** [comment]
The last commit addresses the following issues:

- https://github.com/onnx/models/issues/655
- https://github.com/onnx/models/issues/654

**Pull request merged**
